// NOTE: This file is auto-generated by vite-envs.
// It enables you to access environment variables in your service worker.
// To use it, use `importScripts("swEnv.js")` at the top of your worker file.
// (Assuming your worker file is next to this file)
// Then you can access your environment variables via `self.__VITE_ENVS.MY_VAR`

const envWithValuesInBase64 = {
  "VITE_API_BASE_URL": "IiI=",
  "BASE_URL": "Ii8i",
  "MODE": "InByb2R1Y3Rpb24i",
  "DEV": "ZmFsc2U=",
  "PROD": "dHJ1ZQ==",
  "DD_RUM_APPLICATION_ID": "ImRjZmZiN2Q0LWRmYzctNGI3OS1iYzczLWYwYjk0NTBjMjA2ZSI=",
  "DD_RUM_CLIENT_TOKEN": "InB1YmI0NzVkODUyZDIyZDAwYjJmOTY5Yjc0ZmZlYmZlMmM0Ig==",
  "DD_SITE": "ImRhdGFkb2docS5jb20i",
  "DD_ENV": "IiI=",
  "DD_VERSION": "IiI=",
  "DD_SERVICE": "IiI="
};
const env = {};
Object.keys(envWithValuesInBase64).forEach(function (name) {
    env[name] = JSON.parse(
      new TextDecoder().decode(
        Uint8Array.from(
          atob(envWithValuesInBase64[name]),
          c => c.charCodeAt(0)
        )
      )
    );
});
self.__VITE_ENVS = env;