"""initial_schema

Revision ID: 7405ef902b68
Revises: 
Create Date: 2026-02-19 18:30:30.417197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7405ef902b68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('git_url', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('credentials_ref', sa.String(length=256), nullable=True),
    sa.Column('last_sync_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_url')
    )
    op.create_table('config_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('TERRAFORM', 'KUBERNETES', 'CLOUDFORMATION', 'DOCKER_COMPOSE', 'ANSIBLE', 'HELM', name='resourcetype'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('resource_name', sa.String(length=256), nullable=False),
    sa.Column('expected_config', sa.JSON(), nullable=False),
    sa.Column('actual_config', sa.JSON(), nullable=True),
    sa.Column('last_checked_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_resource_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NO_DRIFT', 'DRIFTED', 'ERROR', 'PENDING', name='driftstatus'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('drift_details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['config_resource_id'], ['config_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drift_report_id', sa.UUID(), nullable=False),
    sa.Column('remediation_type', sa.Enum('MANUAL', 'AUTOMATIC', 'SUGGESTED', name='remediationtype'), nullable=False),
    sa.Column('remediation_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='remediationstatus'), nullable=False),
    sa.Column('remediation_outcome', sa.Enum('SUCCESS', 'PARTIAL_SUCCESS', 'FAILURE', 'ROLLBACK', name='remediationoutcome'), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('executed_by', sa.String(length=256), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rollback_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drift_report_id'], ['drift_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remediation_history')
    op.drop_table('drift_reports')
    op.drop_table('config_resources')
    op.drop_table('repositories')
    # ### end Alembic commands ###
