# Development Dockerfile for .NET User Management Service
# NOTE: Source code must be mounted at /app at runtime for hot reload
# This container only provides the .NET SDK environment and tools

FROM mcr.microsoft.com/dotnet/sdk:10.0

ARG TARGETPLATFORM

WORKDIR /app

COPY ./scripts ./scripts

# Download the latest version of the tracer but don't install yet
RUN . scripts/target.sh && curl -Lo /tmp/datadog-dotnet-apm.deb https://github.com/DataDog/dd-trace-dotnet/releases/download/v3.19.0/datadog-dotnet-apm_3.19.0_${TRACER_ARCHITECTURE}.deb

# Install the tracer
RUN mkdir -p /opt/datadog \
    && mkdir -p /var/log/datadog \
    && dpkg -i /tmp/datadog-dotnet-apm.deb \
    && rm /tmp/datadog-dotnet-apm.deb

ARG DD_GIT_REPOSITORY_URL
ARG DD_GIT_COMMIT_SHA

ENV DD_GIT_REPOSITORY_URL=${DD_GIT_REPOSITORY_URL} 
ENV DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA}

# These environment variables configure the Datadog .NET Tracer
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
ENV DD_DOTNET_TRACER_HOME=/opt/datadog
ENV DD_INTEGRATIONS=/opt/datadog/integrations.json
ENV DD_LOGS_INJECTION=true
ENV DD_RUNTIME_METRICS_ENABLED=true
ENV DD_PROFILING_ENABLED=1
LABEL com.datadoghq.tags.service="user-service"
LABEL com.datadoghq.tags.version=${DD_GIT_COMMIT_SHA}

EXPOSE 8080

# Default entry point for hot reload development
ENTRYPOINT ["dotnet", "watch", "--project", "src/Stickerlandia.UserManagement.Api", "--urls", "http://0.0.0.0:8080"]